#!/bin/sh
set -e

uid=$(stat -c '%u' /infra)
gid=$(stat -c '%g' /infra)

# home may be modified from multiple sources
# try to normalize before using it in paths below
REALHOME=$(realpath $HOME)

mkdir -p $REALHOME
chown $uid:$gid $REALHOME

echo "kbst:x:${uid}:${gid}:Kubestack User:${REALHOME}:/bin/sh" >> /etc/passwd
echo "kbst:x:${gid}:" >> /etc/group

# if docker.sock is mounted, add our user to the socket's group
if test -S "/var/run/docker.sock"; then
    echo "docker:x:$(stat -c '%g' /var/run/docker.sock):kbst" >> /etc/group
fi

# stop running as root to preserve volume mount file ownership
exec runuser -u kbst -- entrypoint_user "$@"
